In [38]:
import pandas as pd
import numpy as np
import joblib

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

In [39]:
X_train_processed = joblib.load("../data/processed/X_train_processed.pkl")
X_test_processed = joblib.load("../data/processed/X_test_processed.pkl")
y_train = joblib.load("../data/processed/y_train.pkl")
y_test = joblib.load("../data/processed/y_test.pkl")

In [40]:
print(X_train_processed.shape)
print(X_test_processed.shape)
print(y_train.shape)
print(y_test.shape)

(5625, 1172)
(1407, 1172)
(5625,)
(1407,)


In [41]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(
    random_state=42,
    max_iter=1000
)

In [42]:
log_reg.fit(X_train_processed, y_train)

print("Logistic Regression model trained successfully!")

Logistic Regression model trained successfully!


In [43]:
y_pred = log_reg.predict(X_test_processed)

y_prob = log_reg.predict_proba(X_test_processed)[:, 1]

In [44]:
print(y_pred[:10])

[0 1 0 0 0 0 0 0 1 0]


In [45]:
print(y_prob[:10])

[0.02687166 0.5645918  0.00678644 0.18710606 0.10926125 0.35741557
 0.00482539 0.19477534 0.72224761 0.01076625]


In [46]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)

In [47]:
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")
print(f"ROC-AUC  : {roc_auc:.4f}")

Accuracy : 0.7896
Precision: 0.6161
Recall   : 0.5535
F1 Score : 0.5831
ROC-AUC  : 0.8331


In [48]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[904 129]
 [167 207]]


In [49]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86      1033
           1       0.62      0.55      0.58       374

    accuracy                           0.79      1407
   macro avg       0.73      0.71      0.72      1407
weighted avg       0.78      0.79      0.79      1407



In [50]:
from sklearn.tree import DecisionTreeClassifier

In [51]:
dt_model = DecisionTreeClassifier(
    random_state=42
)

In [52]:
dt_model.fit(X_train_processed, y_train)

print("Decision Tree trained successfully!")

Decision Tree trained successfully!


In [53]:
dt_pred = dt_model.predict(X_test_processed)

dt_prob = dt_model.predict_proba(X_test_processed)[:, 1]

In [54]:
dt_accuracy = accuracy_score(y_test, dt_pred)
dt_precision = precision_score(y_test, dt_pred)
dt_recall = recall_score(y_test, dt_pred)
dt_f1 = f1_score(y_test, dt_pred)
dt_roc_auc = roc_auc_score(y_test, dt_prob)

In [55]:
print(f"Accuracy : {dt_accuracy:.4f}")
print(f"Precision: {dt_precision:.4f}")
print(f"Recall   : {dt_recall:.4f}")
print(f"F1 Score : {dt_f1:.4f}")
print(f"ROC-AUC  : {dt_roc_auc:.4f}")

Accuracy : 0.7591
Precision: 0.5493
Recall   : 0.5214
F1 Score : 0.5350
ROC-AUC  : 0.6833


In [56]:
dt_cm = confusion_matrix(y_test, dt_pred)

print(dt_cm)

[[873 160]
 [179 195]]


In [57]:
print(classification_report(y_test, dt_pred))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84      1033
           1       0.55      0.52      0.53       374

    accuracy                           0.76      1407
   macro avg       0.69      0.68      0.69      1407
weighted avg       0.76      0.76      0.76      1407



In [58]:
from sklearn.ensemble import RandomForestClassifier

In [59]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train_processed, y_train)

rf_pred = rf_model.predict(X_test_processed)
rf_prob = rf_model.predict_proba(X_test_processed)[:, 1]

In [60]:
rf_accuracy = accuracy_score(y_test, rf_pred)
rf_precision = precision_score(y_test, rf_pred)
rf_recall = recall_score(y_test, rf_pred)
rf_f1 = f1_score(y_test, rf_pred)
rf_roc_auc = roc_auc_score(y_test, rf_prob)

In [61]:
print(f"Accuracy : {rf_accuracy:.4f}")
print(f"Precision: {rf_precision:.4f}")
print(f"Recall   : {rf_recall:.4f}")
print(f"F1 Score : {rf_f1:.4f}")
print(f"ROC-AUC  : {rf_roc_auc:.4f}")

Accuracy : 0.7889
Precision: 0.6314
Recall   : 0.4947
F1 Score : 0.5547
ROC-AUC  : 0.8326


In [62]:
print(confusion_matrix(y_test, rf_pred))

[[925 108]
 [189 185]]


In [63]:
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1033
           1       0.63      0.49      0.55       374

    accuracy                           0.79      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407



In [64]:
!pip install xgboost

In [72]:
from xgboost import XGBClassifier

In [73]:
xgb_model = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42
)

In [74]:
xgb_model.fit(X_train_processed, y_train)

print("XGBoost model trained successfully!")

XGBoost model trained successfully!


In [75]:
xgb_pred = xgb_model.predict(X_test_processed)

xgb_prob = xgb_model.predict_proba(X_test_processed)[:, 1]

In [76]:
xgb_accuracy = accuracy_score(y_test, xgb_pred)
xgb_precision = precision_score(y_test, xgb_pred)
xgb_recall = recall_score(y_test, xgb_pred)
xgb_f1 = f1_score(y_test, xgb_pred)
xgb_roc_auc = roc_auc_score(y_test, xgb_prob)

In [78]:
print(f"Accuracy : {xgb_accuracy:.4f}")
print(f"Precision: {xgb_precision:.4f}")
print(f"Recall   : {xgb_recall:.4f}")
print(f"F1 Score : {xgb_f1:.4f}")
print(f"ROC-AUC  : {xgb_roc_auc:.4f}")

Accuracy : 0.7633
Precision: 0.5584
Recall   : 0.5241
F1 Score : 0.5407
ROC-AUC  : 0.8259


In [79]:
print(confusion_matrix(y_test, xgb_pred))

[[878 155]
 [178 196]]


In [80]:
print(classification_report(y_test, xgb_pred))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84      1033
           1       0.56      0.52      0.54       374

    accuracy                           0.76      1407
   macro avg       0.69      0.69      0.69      1407
weighted avg       0.76      0.76      0.76      1407

